sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
script:
  - 'if [ "${TRAVIS_NODE_VERSION}" = "6" ]; then
       npm run build;
     fi'
  - 'npm test'
after_script:
  - 'istanbul cover --verbose --dir coverage node_modules/.bin/_mocha tests/tests.js -- -u exports -R spec && coveralls < coverage/lcov.info'
