sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '14'
script:
  - 'if [ "${TRAVIS_NODE_VERSION}" = "14" ]; then
       npm run build;
     fi'
  - 'npm test'
after_script:
  - 'istanbul cover --report html node_modules/.bin/_mocha tests -- -u exports -R spec && codecov'
git:
  depth: 1
