name: run-checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Include all major maintenance + active LTS + current Node.js versions.
        # https://github.com/nodejs/Release#release-schedule
        node: [12, 14, 16]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js 16
        uses: actions/setup-node@v1
        with:
          # Always build using the same Node.js version, to ensure consistent
          # results from scripts/iu-mappings.js.
          # This version should be the same as the one used in the
          # publish-on-tag workflow.
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Test
        run: npm test
